#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Nom du projet :
Date de dernière mise à jour :
Auteur(s) :
Version :
Notes :
"""

# Programme principal
######################

# Imports de modules
#--------------------

# Variables globales
#--------------------

# Modules / Fonctions
#--------------------

# Programme
#--------------------
